/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "error": "#ba1a1a",
        "surface-bright": "#fbf9f8",
        "background": "#fbf9f8",
        "on-background": "#1b1c1c",
        "on-tertiary-container": "#bed890",
        "on-error-container": "#93000a",
        "on-surface-variant": "#54433a",
        "surface-tint": "#934b19",
        "outline": "#877369",
        "surface-container-high": "#eae8e7",
        "primary-fixed-dim": "#ffb68c",
        "on-tertiary-fixed": "#131f00",
        "outline-variant": "#dac2b6",
        "on-tertiary": "#ffffff",
        "secondary": "#a23f00",
        "inverse-on-surface": "#f3f0f0",
        "primary": "#6c2f00",
        "on-primary": "#ffffff",
        "secondary-container": "#fc7127",
        "surface-variant": "#e4e2e1",
        "on-tertiary-fixed-variant": "#394d14",
        "secondary-fixed-dim": "#ffb595",
        "inverse-surface": "#303030",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#dcd9d9",
        "on-secondary-fixed-variant": "#7c2e00",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#351000",
        "on-secondary-container": "#5c2000",
        "on-primary-container": "#ffc29f",
        "tertiary": "#33470f",
        "surface-container-highest": "#e4e2e1",
        "surface": "#fbf9f8",
        "tertiary-container": "#4a5f25",
        "inverse-primary": "#ffb68c",
        "secondary-fixed": "#ffdbcd",
        "surface-container": "#f0eded",
        "on-surface": "#1b1c1c",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#b6d088",
        "surface-container-low": "#f5f3f2",
        "primary-fixed": "#ffdbc9",
        "on-primary-fixed": "#321200",
        "on-primary-fixed-variant": "#753401",
        "on-secondary": "#ffffff",
        "primary-container": "#8b4513",
        "tertiary-fixed": "#d2eca2"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Work Sans", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      }
    },
  },
  plugins: [],
}
